const CACHE_NAME="pali-grammar-review-v11-3";const ASSETS=["./","./index.html","./style.css","./app.js","./grammar.json",
  "./sentence-analysis-data.js",
  "./linguistics-tips-data.js",
  "./learning-routes-data.js",
  "./dictionary-sites-data.js",
  "./token-analysis-data.js",
  "./module-guides-data.js",
  "./confusion-pairs-data.js",
  "./sentence-patterns-data.js",
  "./buddhist-reading-data.js",
  "./buddhist-background-data.js",
  "./academic-training-data.js",
  "./terminology-glossary-data.js","./manifest.json","./icon-192.png","./icon-512.png"];self.addEventListener("install",e=>{e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(ASSETS)));self.skipWaiting()});self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));self.clients.claim()});self.addEventListener("fetch",e=>{e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{let cp=r.clone();caches.open(CACHE_NAME).then(ca=>ca.put(e.request,cp));return r}).catch(()=>caches.match("./index.html"))))});